### ISSUE TITLE
Connection console crashed on `\q`

### ISSUE THREAD

**Issue by LeonidVas** [tarantool/tt#476]
Connection console crashed on `\q`
```
┌─[leonid@vasya-hp]─[~/work/mail/tasks/tt_demo/test_env_2]
└──╼ tt connect app1 
   • Connecting to the instance...
   • Connected to /home/leonid/work/mail/tasks/tt_demo/test_env_2/var/run/app1/app1.control

/home/leonid/work/mail/tasks/tt_demo/test_env_2/var/run/app1/app1.control> \q
2023/05/30 13:40:14 whoops! It looks like something is wrong with this version of Tarantool CLI.
Error: Unhandled internal error: runtime error: index out of range [0] with length 0
Version: Tarantool CLI version 1.1.0, linux/amd64. commit: bd52eb5
Stacktrace:
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/lib/go/src/runtime/debug/stack.go:24 +0x65
github.com/tarantool/tt/cli/util.InternalError({0xb85cac, 0x1c}, 0x0?, {0xc00061f3b8, 0x1, 0x1})
	cli/util/util.go:125 +0xa5
main.main.func1()
	cli/main.go:18 +0x5f
panic({0xb35300, 0xc0001700a8})
	/usr/lib/go/src/runtime/panic.go:884 +0x213
github.com/tarantool/tt/cli/connect.getExecutor.func1({0xc000423b90, 0x2})
	cli/connect/console.go:258 +0x689
github.com/c-bata/go-prompt.(*Prompt).Run(0xc000178000)
	/home/leonid/go/pkg/mod/github.com/tarantool/go-prompt@v0.2.6-tarantool/prompt.go:91 +0x77f
github.com/tarantool/tt/cli/connect.(*Console).Run(0xc0003be500)
	cli/connect/console.go:145 +0x1aa
github.com/tarantool/tt/cli/connect.runConsole({{0xb6e933, 0x4}, {0xc000036f50, 0x49}, {0x0, 0x0}, {0x0, 0x0}, {{0x0, 0x0}, ...}}, ...)
	cli/connect/connect.go:159 +0x125
github.com/tarantool/tt/cli/connect.Connect({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, 0x0, {0x0, 0x0}, {0x0, ...}, ...}, ...)
	cli/connect/connect.go:92 +0xdc
github.com/tarantool/tt/cli/cmd.internalConnectModule(0xad7280?, {0xc0003e2e90, 0x1, 0x1})
	cli/cmd/connect.go:240 +0x335
github.com/tarantool/tt/cli/modules.RunCmd(0x114a080, {0xc0003e8810, 0xa}, 0xc0003c4100?, 0xc78ba8, {0xc0003e2e90, 0x1, 0x1})
	cli/modules/run.go:36 +0x90
github.com/tarantool/tt/cli/cmd.NewConnectCmd.func1(0xc0003c2c80?, {0xc0003e2e90, 0x1, 0x1})
	cli/cmd/connect.go:60 +0x94
github.com/spf13/cobra.(*Command).execute(0xc0003c2c80, {0xc0000221a0, 0x1, 0x1})
	/home/leonid/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003b9400)
	/home/leonid/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/leonid/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/tarantool/tt/cli/cmd.Execute()
	cli/cmd/root.go:176 +0x25
main.main()
	cli/main.go:23 +0x45

```

**Comment by 0x501D** [comment]
Dirty patch:
```diff
diff --git a/cli/connect/console.go b/cli/connect/console.go
index 9f42c3a..cf3bf40 100644
--- a/cli/connect/console.go
+++ b/cli/connect/console.go
@@ -255,7 +255,13 @@ func getExecutor(console *Console) prompt.Executor {
                                log.Fatalf("Failed to execute command: %s", err)
                        }
                } else {
-                       data = results[0]
+                       if len(results) != 0 {
+                               data = results[0]
+                       } else {
+                               console.Close()
+                               log.Infof("Conn closed")
+                               os.Exit(0)
+                       }
                }
 
                fmt.Printf("%s\n", data)
```

```sh
$ ./tt connect a
   • Connecting to the instance...
   • Connected to /home/void/git/tnt/tt/var/run/a/a.control

/home/void/git/tnt/tt/var/run/a/a.control> \q
   • Conn closed  
```

**Comment by LeonidVas** [comment]
related with https://github.com/tarantool/cartridge-cli/issues/705
